project:
  type: website
  output-dir: docs

website:
  title: "Old vs New Trance Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Track-Level-Features.qmd
        text: Track-Level-Features
      - href: Chroma-Features.qmd
        text: Chroma-Features
      - href: Clustering.qmd
        text: Clustering
      - href: Contribution.qmd
        text: Conclusion

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

