---
title: "Sam Verbeek, Computational Musicology, Old Trance vs New Trance"
---

```{r}


library(tidyverse)
library(tibble)
library(ggplot2)
library(tidymodels)
library(ggdendro)
library(heatmaply)

Final_Corpus <- read_csv("~/Downloads/Final_Corpus.csv")

#seperate old trance and new trance
Trance_Corpus <- Final_Corpus %>%
  mutate(`Release Date` = as.numeric(substr(`Release Date`, 1, 4))) %>%
  mutate(Category = ifelse(`Release Date` < 2015, "Old Trance", "New Trance"))

#seperate my own tracks from the old and new trance categories
Trance_Corpus <- Trance_Corpus %>%
  mutate(Category = ifelse(`Artist Name(s)` == "Bekí", "Bekí", Category))

```

#How has the sound of trance music evolved from the early 2000's to modern day trance in terms of audio-features and where does my sound fit in?

##Background

Trance music is a subgenre of electronic dance music that emerged in the late 1980s and gained major popularity throughout the 1990s and early 2000s. It is typically characterized by a fast tempo (often around 125–150 BPM), repeating melodic phrases, and a strong focus on building emotional intensity through gradual layering and breakdowns. Rather than relying on lyrical content, trance often emphasizes atmosphere and progression, aiming to create a hypnotic or “immersive” listening experience.

###Corpus

For this project, I created a dataset of 62 trance tracks divided into two equal groups: classic trance and modern trance. The classic tracks mainly come from the late 1990s and early 2000s, while the modern tracks represent more recent releases. My track selection of the classic trance was based on spotify playlists with names like “trance hits” or “top 100 trance” which were made before 2013. My track selection of the modern trance was based on my own knowledge of songs, because I am really invested in this part of the genre. I chose these two categories to explore how the trance genre has changed over time, especially in terms of sound, structure, and production style. The classic trance tracks were selected because they are known for their melodic focus, longer breakdowns, and more gradual build-ups. On the other hand, modern trance tracks tend to be faster, louder, and more focused on maintaining a high level of energy throughout the track. By comparing these two groups, I aimed to identify clear differences between older and newer production approaches. In addition to these tracks, I also included a small number of my own productions (Bekí). These tracks were produced using a digital audio workstation, where I created the sounds using synthesizers and arranged them into full tracks. They are mainly influenced by modern trance, but also include some elements of classic trance, such as melodic progression. The purpose of including my own tracks is not to analyse them separately, but to see where they fit within the broader trance genre. This helps to connect the analytical part of the project to my own production practice.\
\
